# Generated by Django 3.0.1 on 2020-01-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50, verbose_name='Instituição')),
                ('anoInicial', models.IntegerField(verbose_name='Ano inicial')),
                ('anoFim', models.IntegerField(verbose_name='Ano Final')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_tec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50, verbose_name='Instituição')),
                ('ano', models.CharField(max_length=10, verbose_name='Ano')),
                ('carga_horaria', models.CharField(max_length=20, verbose_name='Carga horaria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('anoInicial', models.IntegerField(verbose_name='Ano inicial')),
                ('anoFim', models.IntegerField(verbose_name='Ano Final')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('anoInicial', models.IntegerField(verbose_name='Ano inicial')),
                ('anoFim', models.IntegerField(verbose_name='Ano Final')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Titulo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('imagens', models.ImageField(upload_to='', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Titulo')),
                ('data', models.DateField(verbose_name='Data de publicação')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('imagens', models.ImageField(upload_to='', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('data', models.CharField(max_length=50, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('apresentacao', models.TextField(verbose_name='Apresentação')),
                ('servico', models.CharField(max_length=50, verbose_name='Meus serviços')),
                ('conhecimento', models.CharField(max_length=50, verbose_name='Conhecimentos')),
                ('profissao', models.CharField(max_length=30, verbose_name='Profissão')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagran', models.URLField(verbose_name='Instagran')),
                ('linkdin', models.URLField(verbose_name='Linkdin')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Curso')),
                ('curso_tec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Curso_tec')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Endereco')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Estagio')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Historico')),
                ('portifolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Portifolio')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_App.Post')),
            ],
        ),
    ]
